spring:
  application:
    name: movies-platform
  datasource:
    url: jdbc:postgresql://localhost:5432/movies
    username: movies
    password: movies
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8080

app:
  csv:
    movie-file: ./data/movies.csv
    rating-file: ./data/ratings.csv
  import:
    auto: true

logging:
  level:
    org.hibernate.SQL: warn
    org.springframework: info

